<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.example</groupId>
    <artifactId>lab7</artifactId>
    <version>1.0-SNAPSHOT</version>

    <dependencies>
        <dependency>
            <groupId>org.json</groupId>
            <artifactId>json</artifactId>
            <version>20230227</version>
        </dependency>

        <dependency>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-controls</artifactId>
            <version>17.0.6</version>
        </dependency>
        <dependency>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-fxml</artifactId>
            <version>17.0.6</version>
        </dependency>

    </dependencies>

    <properties>
        <maven.compiler.source>22</maven.compiler.source>
        <maven.compiler.target>22</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <FlowPane fx:controller="com.example.whackamole.HitMouseController"
              xmlns:fx="http://javafx.com/fxml/1" alignment="center" hgap="5" vgap="5">
        <HBox fx:id="hbHead" prefWidth="560" prefHeight="40">
            <Label fx:id="labelTime" prefWidth="200" prefHeight="40" alignment="center"
                   text="00:00" />
            <Button fx:id="btnStart" prefWidth="160" prefHeight="40" alignment="center"
                    text="Start" />
            <Label fx:id="labelCount" prefWidth="200" prefHeight="40" alignment="center"
                   text="Count" />
        </HBox>
        <GridPane fx:id="gpGrass" prefWidth="560" prefHeight="630" />
    </FlowPane>



</project>

