spring.application.name=FinalProject_demo
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/cs209a_grace
# jdbc:postgresql://localhost:5432/cs209_final
spring.datasource.username=postgres
spring.datasource.password=huarui66
# post2053
# huarui66

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

logging.level.root=INFO
logging.level.cs209a.finalproject_demo=DEBUG
logging.level.org.springframework.jdbc.core=TRACE

data.directory=./data_2000_new
app.name=StackOverflow Java Questions Analyzer
app.version=1.0.0
